#!/bin/sh
set -e

# create directories
mkdir -p \
    /config/{log,data/plugins/configurations,data/transcodes,cache} \
    /data \
    /transcode

# permissions
lsiown abc:abc \
    /config \
    /config/* \
    /config/data/plugins \
    /config/data/plugins/configurations \
    /config/data/transcodes \
    /transcode

# first arg is `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- jellyfin "$@"
fi

# allow the container to be started with `--user`
if [ "$(id -u)" = '0' ]; then
    find . \! -user jellyfin -exec chown jellyfin '{}' +
    exec su-exec jellyfin "$0" "$@"
fi

exec "$@"
